#!/bin/bash
# write-trace.sh - Deterministic trace assembly for an increment
# Reads contract, attempts, verdict, gate results, and metrics to produce
# a structured YAML trace at traces/increment-{N}.yaml.
#
# Usage: bash scripts/write-trace.sh <increment-number>

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: bash scripts/write-trace.sh <increment-number>"
  exit 2
fi

INCREMENT="$1"
SUPERTEAM_DIR=".superteam"

# Source shared library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

# Input files
CONTRACT="$SUPERTEAM_DIR/contracts/increment-${INCREMENT}.md"
ATTEMPTS="$SUPERTEAM_DIR/attempts/increment-${INCREMENT}.md"
VERDICT="$SUPERTEAM_DIR/verdicts/increment-${INCREMENT}.md"
GATE_RESULTS="$SUPERTEAM_DIR/gate-results/increment-${INCREMENT}.json"

# Output
TRACES_DIR="$SUPERTEAM_DIR/traces"
OUTPUT="$TRACES_DIR/increment-${INCREMENT}.yaml"

mkdir -p "$TRACES_DIR"

# Parse fields from contract
CONTRACT_NAME=""
CONTRACT_STATUS=""
SPEC_ITEMS=""
if [ -f "$CONTRACT" ]; then
  CONTRACT_NAME=$(parse_yaml_field "$CONTRACT" "name")
  CONTRACT_STATUS=$(parse_yaml_field "$CONTRACT" "status")
  SPEC_ITEMS=$(parse_yaml_field "$CONTRACT" "spec_items")
fi

# Parse verdict
VERDICT_VALUE=""
if [ -f "$VERDICT" ]; then
  VERDICT_VALUE=$(parse_yaml_field "$VERDICT" "verdict")
fi

# Parse gate results summary
GATES_TOTAL=0
GATES_PASSED=0
GATES_FAILED=0
GATES_ALL_PASSED="false"
if [ -f "$GATE_RESULTS" ]; then
  GATES_TOTAL=$(python3 -c "import json; d=json.load(open('$GATE_RESULTS')); print(d.get('total',0))" 2>/dev/null || echo 0)
  GATES_PASSED=$(python3 -c "import json; d=json.load(open('$GATE_RESULTS')); print(d.get('passed',0))" 2>/dev/null || echo 0)
  GATES_FAILED=$(python3 -c "import json; d=json.load(open('$GATE_RESULTS')); print(d.get('failed',0))" 2>/dev/null || echo 0)
  GATES_ALL_PASSED=$(python3 -c "import json; d=json.load(open('$GATE_RESULTS')); print(str(d.get('all_passed',False)).lower())" 2>/dev/null || echo "false")
fi

# Count attempts
ATTEMPT_COUNT=0
if [ -f "$ATTEMPTS" ]; then
  ATTEMPT_COUNT=$(grep -c '^## Attempt' "$ATTEMPTS" 2>/dev/null || echo 0)
fi

# Files modified (from git diff for this increment's commit)
FILES_MODIFIED=""
COMMIT_MSG=$(git log --oneline --all --grep="increment-${INCREMENT}" -1 2>/dev/null || true)
if [ -n "$COMMIT_MSG" ]; then
  COMMIT_HASH=$(echo "$COMMIT_MSG" | awk '{print $1}')
  FILES_MODIFIED=$(git diff-tree --no-commit-id --name-only -r "$COMMIT_HASH" 2>/dev/null | sed 's/^/  - /' || true)
fi

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Write YAML trace
cat > "$OUTPUT" <<YAML
# Trace: Increment ${INCREMENT}
# Generated by write-trace.sh at ${TIMESTAMP}

increment: ${INCREMENT}
name: "${CONTRACT_NAME}"
timestamp: "${TIMESTAMP}"

contract:
  status: "${CONTRACT_STATUS}"
  spec_items: ${SPEC_ITEMS:-"[]"}

execution:
  attempt_count: ${ATTEMPT_COUNT}
  verdict: "${VERDICT_VALUE}"

gates:
  total: ${GATES_TOTAL}
  passed: ${GATES_PASSED}
  failed: ${GATES_FAILED}
  all_passed: ${GATES_ALL_PASSED}

files_modified:
${FILES_MODIFIED:- - "(none detected)"}
YAML

echo "Trace written to: $OUTPUT"
exit 0
